language: node_js
node_js:
  - "node"

cache: npm

script: npm run build

deploy:
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  keep_history: false
  target_branch: gh-pages
  local_dir: ./dist/
  on:
    branch: master