import type { SidebarConfig } from "@vuepress/theme-default";

export const sidebarEn: SidebarConfig = {
  "/about/": [
    {
      text: "About",
      children: [
        "/about/README.md",
        "/about/techstack.md",
        "/about/links.md",
        "/about/blog.md",
      ],
    },
  ],
  "/notes/": [
    {
      text: "📝 Notes",
      link: "/notes/README.md",
      children: [
        {
          text: "Algorithm",
          children: [
            "/notes/Algorithm/Algorithm Bloom Filter.md",
            "/notes/Algorithm/Algorithm Disjoint Set.md",
            "/notes/Algorithm/Algorithm Fast Power.md",
            "/notes/Algorithm/Algorithm KMP.md",
            "/notes/Algorithm/Algorithm Monotonic Stack.md",
            "/notes/Algorithm/Algorithm RB-Tree.md",
            "/notes/Algorithm/Algorithm Regular Expression.md",
            "/notes/Algorithm/Algorithm Sliding Window.md",
            "/notes/Algorithm/Online Judge IO.md",
          ],
        },
        {
          text: "C++",
          children: [
            "/notes/C++/C++ Const.md",
            "/notes/C++/C++ File I&O.md",
            "/notes/C++/C++ Object Layout.md",
            "/notes/C++/C++ Operator Overload.md",
            "/notes/C++/C++ Polymorphism.md",
            "/notes/C++/C++ STL algorithm.md",
            "/notes/C++/C++ STL map.md",
            "/notes/C++/C++ STL multimap.md",
            "/notes/C++/C++ STL priority_queue.md",
            "/notes/C++/C++ STL set.md",
            "/notes/C++/C++ STL string.md",
            "/notes/C++/C++ STL unordered_map.md",
            "/notes/C++/C++ STL vector.md",
            "/notes/C++/C++ Smart Pointer.md",
            "/notes/C++/C++ Template & Genericity.md",
          ],
        },
        {
          text: "Compiler",
          children: [
            "/notes/Compiler/ANTLR Basic.md",
            "/notes/Compiler/Compiler LLVM Architecture.md",
            "/notes/Compiler/Compiler Multi-version GCC.md",
          ],
        },
        {
          text: "Cryptography",
          children: [
            "/notes/Cryptography/Cryptography Certbot.md",
            "/notes/Cryptography/Cryptography Digital Signature & PKCS7.md",
            "/notes/Cryptography/Cryptography GPG.md",
            "/notes/Cryptography/Cryptography JWT.md",
            "/notes/Cryptography/Cryptography Keystore & Certificates.md",
            "/notes/Cryptography/Cryptography OAuth 2.0.md",
            "/notes/Cryptography/Cryptography Symmetric & Asymmetric Encryption.md",
            "/notes/Cryptography/Cryptography TLS.md",
          ],
        },
        { text: "DevOps", children: ["/notes/DevOps/DevOps Travis CI.md"] },
        {
          text: "Docker",
          children: [
            "/notes/Docker/Docker Image & Storage Management.md",
            "/notes/Docker/Docker Image.md",
            "/notes/Docker/Docker Libcontainer.md",
            "/notes/Docker/Docker Multi-Stage Build.md",
            "/notes/Docker/Docker Network.md",
            "/notes/Docker/Docker Orchestration & Deployment.md",
            "/notes/Docker/Docker Overview.md",
            "/notes/Docker/Docker Service Building.md",
            "/notes/Docker/Docker Volume & Network Usage.md",
            "/notes/Docker/Docker Volume.md",
            "/notes/Docker/Linux Control Group.md",
            "/notes/Docker/Linux Namespace.md",
          ],
        },
        {
          text: "Git",
          children: [
            "/notes/Git/Git Branch & Merge.md",
            "/notes/Git/Git Cached.md",
            "/notes/Git/Git Cherry Pick.md",
            "/notes/Git/Git Diff.md",
            "/notes/Git/Git Patch.md",
            "/notes/Git/Git Proxy.md",
            "/notes/Git/Git Rebase.md",
            "/notes/Git/Git Reset.md",
            "/notes/Git/Git Stash.md",
            "/notes/Git/Git Theme for Git-Bash.md",
          ],
        },
        {
          text: "Java",
          children: [
            "/notes/Java/JVM Synchronized.md",
            "/notes/Java/JVM Volatile.md",
            "/notes/Java/Java Annotation.md",
            "/notes/Java/Java BIO & NIO.md",
            "/notes/Java/Java Class Path.md",
            "/notes/Java/Java Condition & LockSupport.md",
            "/notes/Java/Java Current Timestamp.md",
            "/notes/Java/Java Deep Copy.md",
            "/notes/Java/Java Environment Configuration.md",
            "/notes/Java/Java Equals.md",
            "/notes/Java/Java Exporting JAR.md",
            "/notes/Java/Java Javadoc.md",
            "/notes/Java/Java Lock.md",
            "/notes/Java/Java Maven.md",
            "/notes/Java/Java References.md",
            "/notes/Java/Java Reflection.md",
            "/notes/Java/Java String Split.md",
            "/notes/Java/Java Thread Pool.md",
            "/notes/Java/Java Thread.md",
            "/notes/Java/Tomcat Class Loader.md",
            "/notes/Java/Tomcat Container.md",
          ],
        },
        {
          text: "MS Office",
          children: [
            "/notes/MS Office/MS Office Add-in Dev.md",
            "/notes/MS Office/MS Office Application.md",
          ],
        },
        {
          text: "MySQL",
          children: [
            "/notes/MySQL/InnoDB Architecture.md",
            "/notes/MySQL/InnoDB Backup.md",
            "/notes/MySQL/InnoDB Checkpoint.md",
            "/notes/MySQL/InnoDB Critical Features.md",
            "/notes/MySQL/InnoDB Files.md",
            "/notes/MySQL/InnoDB Index.md",
            "/notes/MySQL/InnoDB Insert Buffer.md",
            "/notes/MySQL/InnoDB Lock.md",
            "/notes/MySQL/InnoDB Partition Table.md",
            "/notes/MySQL/InnoDB Table Storage.md",
            "/notes/MySQL/MySQL Server Configuration.md",
            "/notes/MySQL/MySQL Storage Engine.md",
          ],
        },
        {
          text: "Network",
          children: [
            "/notes/Network/Network ARP.md",
            "/notes/Network/Network FTP.md",
            "/notes/Network/Network GitHub Accelerating.md",
            "/notes/Network/Network HTTP Message Format.md",
            "/notes/Network/Network HTTP POSTing form.md",
            "/notes/Network/Network Proxy Server.md",
            "/notes/Network/Network SCP.md",
            "/notes/Network/Network SSH.md",
            "/notes/Network/Network TCP Congestion Control.md",
            "/notes/Network/Network TCP Connection Management.md",
            "/notes/Network/Network TCP Flow Control.md",
            "/notes/Network/Network TCP Retransmission.md",
            "/notes/Network/Network Traceroute.md",
            "/notes/Network/Network V2Ray.md",
            "/notes/Network/Network WebSocket.md",
            "/notes/Network/Network Windows 10 Mail APP.md",
            "/notes/Network/Network frp.md",
          ],
        },
        {
          text: "Operating System",
          children: [
            "/notes/Operating System/Linux Kernel Compilation.md",
            "/notes/Operating System/Linux Multi-OS.md",
            "/notes/Operating System/Linux Mutex&Condition.md",
            "/notes/Operating System/Linux Operations.md",
            "/notes/Operating System/Linux Package Manager.md",
            "/notes/Operating System/Linux Process Manipulation.md",
            "/notes/Operating System/Linux User ID.md",
            "/notes/Operating System/Linux execve.md",
            "/notes/Operating System/OS Compile and Link.md",
            "/notes/Operating System/OS Dynamic Linking.md",
            "/notes/Operating System/OS ELF.md",
            "/notes/Operating System/OS Image.md",
            "/notes/Operating System/OS Loading.md",
            "/notes/Operating System/OS Shared Library Organization.md",
            "/notes/Operating System/OS Static Linking.md",
            "/notes/Operating System/Syzkaller Architecture.md",
            "/notes/Operating System/Syzkaller Description Syntax.md",
            "/notes/Operating System/Syzkaller Usage.md",
            "/notes/Operating System/Ubuntu Desktop Recover (Python).md",
            "/notes/Operating System/WSL CentOS8.md",
          ],
        },
        {
          text: "PostgreSQL",
          children: [
            "/notes/PostgreSQL/PostgreSQL Executor Append.md",
            "/notes/PostgreSQL/PostgreSQL Executor Group.md",
            "/notes/PostgreSQL/PostgreSQL Executor Limit.md",
            "/notes/PostgreSQL/PostgreSQL Executor Material.md",
            "/notes/PostgreSQL/PostgreSQL Executor Nest Loop Join.md",
            "/notes/PostgreSQL/PostgreSQL Executor Result.md",
            "/notes/PostgreSQL/PostgreSQL Executor Sequential Scan.md",
            "/notes/PostgreSQL/PostgreSQL Executor Sort.md",
            "/notes/PostgreSQL/PostgreSQL Executor Unique.md",
            "/notes/PostgreSQL/PostgreSQL GUC.md",
            "/notes/PostgreSQL/PostgreSQL Locking.md",
            "/notes/PostgreSQL/PostgreSQL Query Execution.md",
          ],
        },
        {
          text: "Productivity",
          children: [
            "/notes/Productivity/LaTeX.md",
            "/notes/Productivity/Venn Diagram.md",
            "/notes/Productivity/VuePress.md",
          ],
        },
        {
          text: "Solidity",
          children: [
            "/notes/Solidity/Solidity ABI Specification.md",
            "/notes/Solidity/Solidity Contracts.md",
            "/notes/Solidity/Solidity Expressions and Control Structures.md",
            "/notes/Solidity/Solidity Layout and Structure.md",
            "/notes/Solidity/Solidity Remix IDE.md",
            "/notes/Solidity/Solidity Slither.md",
            "/notes/Solidity/Solidity Types.md",
            "/notes/Solidity/Solidity Units and Globally Variables.md",
          ],
        },
        {
          text: "Vue.js",
          children: ["/notes/Vue.js/Vue.js Environment Variable.md"],
        },
        {
          text: "Web",
          children: [
            "/notes/Web/Web CORS.md",
            "/notes/Web/Web OpenAPI Specification.md",
          ],
        },
        {
          text: "Wireless",
          children: [
            "/notes/Wireless/Wireless WEP Cracking by Aircrack-ng.md",
            "/notes/Wireless/Wireless WPS Cracking by Reaver.md",
            "/notes/Wireless/Wireless Wifiphisher.md",
          ],
        },
      ],
    },
  ],
  "/how-linux-works-notes/": [
    {
      text: "🐧 How Linux Works",
      link: "/how-linux-works-notes/README.md",
      children: [
        "/how-linux-works-notes/Chapter 1 - The Big Picture.md",
        "/how-linux-works-notes/Chapter 2 - Basic Commands and Directory Hierarchy.md",
        "/how-linux-works-notes/Chapter 3 - Devices.md",
        "/how-linux-works-notes/Chapter 4.1 - Partitioning Disk Devices.md",
        "/how-linux-works-notes/Chapter 4.2 - Filesystems.md",
        "/how-linux-works-notes/Chapter 4.3-4.5 - Swap Space & Inside a Traditional Filesystem.md",
        "/how-linux-works-notes/Chapter 5 - How the Linux Kernel Boots.md",
        "/how-linux-works-notes/Chapter 7 - System Configuration.md",
        "/how-linux-works-notes/Chapter 8 - A Closer Look at Processes and Resource Utilization.md",
        "/how-linux-works-notes/Chapter 9 - Understanding your Network and ites Configuration.md",
        "/how-linux-works-notes/Chapter 10 - Network Applications and Services.md",
        "/how-linux-works-notes/Chapter 11 - Introduction to Shell Scripts.md",
        "/how-linux-works-notes/Chapter 12 - Moving Files Across the Network.md",
        "/how-linux-works-notes/Chapter 15 - Development Tools.md",
        "/how-linux-works-notes/Chapter 16 - Introduction to Compiling Software From C Source Code.md",
      ],
    },
  ],
  "/linux-kernel-comments-notes/": [
    {
      text: "🐧 Linux Kernel Comments",
      link: "/linux-kernel-comments-notes/README.md",
      children: [
        {
          text: "Chapter 2 - 微型计算机组成结构",
          children: [
            "/linux-kernel-comments-notes/Chapter 2 - 微型计算机组成结构/Chapter 2 - 微型计算机组成结构.md",
          ],
        },
        {
          text: "Chapter 3 - 内核编程语言和环境",
          children: [
            "/linux-kernel-comments-notes/Chapter 3 - 内核编程语言和环境/Chapter 3 - 内核编程语言和环境.md",
          ],
        },
        {
          text: "Chapter 4 - 80X86 保护模式及其编程",
          children: [
            "/linux-kernel-comments-notes/Chapter 4 - 80X86 保护模式及其编程/Chapter 4.1-4.2 - 80X86 & 保护模式内存管理.md",
            "/linux-kernel-comments-notes/Chapter 4 - 80X86 保护模式及其编程/Chapter 4.3 - 分段机制.md",
            "/linux-kernel-comments-notes/Chapter 4 - 80X86 保护模式及其编程/Chapter 4.4 - 分页机制.md",
            "/linux-kernel-comments-notes/Chapter 4 - 80X86 保护模式及其编程/Chapter 4.5 - 保护.md",
            "/linux-kernel-comments-notes/Chapter 4 - 80X86 保护模式及其编程/Chapter 4.6 - 中断和异常处理.md",
            "/linux-kernel-comments-notes/Chapter 4 - 80X86 保护模式及其编程/Chapter 4.7 - 任务管理.md",
            "/linux-kernel-comments-notes/Chapter 4 - 80X86 保护模式及其编程/Chapter 4.8 - 保护模式编程初始化.md",
            "/linux-kernel-comments-notes/Chapter 4 - 80X86 保护模式及其编程/Chapter 4.9 - 一个简单的多任务内核实例.md",
          ],
        },
        {
          text: "Chapter 5 - Linux 内核体系结构",
          children: [
            "/linux-kernel-comments-notes/Chapter 5 - Linux 内核体系结构/Chapter 5.1-5.2 - Linux 内核模式 & 体系结构.md",
            "/linux-kernel-comments-notes/Chapter 5 - Linux 内核体系结构/Chapter 5.3 - Linux 内核对内存的管理和使用.md",
            "/linux-kernel-comments-notes/Chapter 5 - Linux 内核体系结构/Chapter 5.4-5.6 - 中断机制 & 系统调用 & 系统时间和定时.md",
            "/linux-kernel-comments-notes/Chapter 5 - Linux 内核体系结构/Chapter 5.7-5.9 - Linux 进程控制 & 堆栈使用 & 文件系统.md",
          ],
        },
        {
          text: "Chapter 6 - 引导启动程序 (boot)",
          children: [
            "/linux-kernel-comments-notes/Chapter 6 - 引导启动程序 (boot)/Chapter 6 - 引导启动程序 (boot).md",
          ],
        },
        {
          text: "Chapter 7 - 初始化程序 (init)",
          children: [
            "/linux-kernel-comments-notes/Chapter 7 - 初始化程序 (init)/Chapter 7 - 初始化程序 (init).md",
          ],
        },
        {
          text: "Chapter 8 - 内核代码",
          children: [
            "/linux-kernel-comments-notes/Chapter 8 - 内核代码/Chapter 8.1 - 内核代码 总体功能.md",
            "/linux-kernel-comments-notes/Chapter 8 - 内核代码/Chapter 8.2 - asm.s 程序.md",
            "/linux-kernel-comments-notes/Chapter 8 - 内核代码/Chapter 8.3 - traps.c 程序.md",
            "/linux-kernel-comments-notes/Chapter 8 - 内核代码/Chapter 8.4 - sys_call.s 程序.md",
            "/linux-kernel-comments-notes/Chapter 8 - 内核代码/Chapter 8.5 - mktime.c 程序.md",
            "/linux-kernel-comments-notes/Chapter 8 - 内核代码/Chapter 8.6 - sched.c 程序.md",
            "/linux-kernel-comments-notes/Chapter 8 - 内核代码/Chapter 8.7 - signal.c 程序.md",
            "/linux-kernel-comments-notes/Chapter 8 - 内核代码/Chapter 8.8 - exit.c 程序.md",
            "/linux-kernel-comments-notes/Chapter 8 - 内核代码/Chapter 8.9 - fork.c 程序.md",
            "/linux-kernel-comments-notes/Chapter 8 - 内核代码/Chapter 8.10 - sys.c 程序.md",
          ],
        },
        {
          text: "Chapter 9 - 块设备驱动程序",
          children: [
            "/linux-kernel-comments-notes/Chapter 9 - 块设备驱动程序/Chapter 9.1 - 块设备驱动程序 总体功能.md",
            "/linux-kernel-comments-notes/Chapter 9 - 块设备驱动程序/Chapter 9.2 - blk.h 文件.md",
            "/linux-kernel-comments-notes/Chapter 9 - 块设备驱动程序/Chapter 9.3 - hd.c 程序.md",
            "/linux-kernel-comments-notes/Chapter 9 - 块设备驱动程序/Chapter 9.4 - ll_rw_blk.c 程序.md",
            "/linux-kernel-comments-notes/Chapter 9 - 块设备驱动程序/Chapter 9.5 - ramdisk.c 程序.md",
          ],
        },
        {
          text: "Chapter 10 - 字符设备驱动程序",
          children: [
            "/linux-kernel-comments-notes/Chapter 10 - 字符设备驱动程序/Chapter 10.1 - 字符设备驱动程序 总体功能.md",
            "/linux-kernel-comments-notes/Chapter 10 - 字符设备驱动程序/Chapter 10.2 - keyboard.S 程序.md",
            "/linux-kernel-comments-notes/Chapter 10 - 字符设备驱动程序/Chapter 10.3 - console.c 程序.md",
            "/linux-kernel-comments-notes/Chapter 10 - 字符设备驱动程序/Chapter 10.4 - serial.c 程序.md",
            "/linux-kernel-comments-notes/Chapter 10 - 字符设备驱动程序/Chapter 10.5 - rs_io.s 程序.md",
            "/linux-kernel-comments-notes/Chapter 10 - 字符设备驱动程序/Chapter 10.6 - tty_io.c 程序.md",
            "/linux-kernel-comments-notes/Chapter 10 - 字符设备驱动程序/Chapter 10.7 - tty_ioctl.c 程序.md",
          ],
        },
        {
          text: "Chapter 12 - 文件系统",
          children: [
            "/linux-kernel-comments-notes/Chapter 12 - 文件系统/Chapter 12.1 - 文件系统 总体功能.md",
            "/linux-kernel-comments-notes/Chapter 12 - 文件系统/Chapter 12.2 - buffer.c 程序.md",
            "/linux-kernel-comments-notes/Chapter 12 - 文件系统/Chapter 12.3 - bitmap.c 程序.md",
            "/linux-kernel-comments-notes/Chapter 12 - 文件系统/Chapter 12.4 - truncate.c 程序.md",
            "/linux-kernel-comments-notes/Chapter 12 - 文件系统/Chapter 12.5 - inode.c 程序.md",
            "/linux-kernel-comments-notes/Chapter 12 - 文件系统/Chapter 12.6 - super.c 程序.md",
            "/linux-kernel-comments-notes/Chapter 12 - 文件系统/Chapter 12.7 - namei.c 程序.md",
            "/linux-kernel-comments-notes/Chapter 12 - 文件系统/Chapter 12.9 - block_dev.c 程序.md",
            "/linux-kernel-comments-notes/Chapter 12 - 文件系统/Chapter 12.10 - file_dev.c 程序.md",
            "/linux-kernel-comments-notes/Chapter 12 - 文件系统/Chapter 12.11 - pipe.c 程序.md",
            "/linux-kernel-comments-notes/Chapter 12 - 文件系统/Chapter 12.12 - char_dev.c 程序.md",
            "/linux-kernel-comments-notes/Chapter 12 - 文件系统/Chapter 12.13 - read_write.c 程序.md",
            "/linux-kernel-comments-notes/Chapter 12 - 文件系统/Chapter 12.14 - open.c 程序.md",
            "/linux-kernel-comments-notes/Chapter 12 - 文件系统/Chapter 12.15 - exec.c 程序.md",
            "/linux-kernel-comments-notes/Chapter 12 - 文件系统/Chapter 12.16 - stat.c 程序.md",
            "/linux-kernel-comments-notes/Chapter 12 - 文件系统/Chapter 12.17 - fcntl.c 程序.md",
            "/linux-kernel-comments-notes/Chapter 12 - 文件系统/Chapter 12.18 - ioctl.c 程序.md",
            "/linux-kernel-comments-notes/Chapter 12 - 文件系统/Chapter 12.19 - select.c 程序.md",
          ],
        },
      ],
    },
  ],
  "/linux-kernel-development-notes/": [
    {
      text: "🐧 Linux Kernel Development",
      link: "/linux-kernel-development-notes/README.md",
      children: [
        "/linux-kernel-development-notes/Chapter 1 - Linux 内核简介.md",
        "/linux-kernel-development-notes/Chapter 2 - 从内核出发.md",
        "/linux-kernel-development-notes/Chapter 3 - 进程管理.md",
        "/linux-kernel-development-notes/Chapter 4 - 进程调度.md",
        "/linux-kernel-development-notes/Chapter 5 - 系统调用.md",
        "/linux-kernel-development-notes/Chapter 7 - 中断和中断处理.md",
        "/linux-kernel-development-notes/Chapter 9 - 内核同步介绍.md",
        "/linux-kernel-development-notes/Chapter 10 - 内核同步方法.md",
        "/linux-kernel-development-notes/Chapter 11 - 定时器和时间管理.md",
        "/linux-kernel-development-notes/Chapter 13 - 虚拟文件系统.md",
        "/linux-kernel-development-notes/Chapter 14 - 块 IO 层.md",
        "/linux-kernel-development-notes/Chapter 16 - 页高速缓存和页回写.md",
      ],
    },
  ],
  "/uc-os-ii-code-notes/": [
    {
      text: "🐤 μc/OS-II Source Code",
      link: "/uc-os-ii-code-notes/README.md",
      children: [
        {
          text: "Chapter 1 - 嵌入式系统导论",
          children: [
            "/uc-os-ii-code-notes/Chapter 1 - 嵌入式系统导论/Chapter 1 - 嵌入式系统导论.md",
          ],
        },
        {
          text: "Chapter 2 - 嵌入式操作系统中的基本概念",
          children: [
            "/uc-os-ii-code-notes/Chapter 2 - 嵌入式操作系统中的基本概念/Chapter 2 - 嵌入式操作系统中的基本概念.md",
          ],
        },
        {
          text: "Chapter 3 - 任务管理",
          children: [
            "/uc-os-ii-code-notes/Chapter 3 - 任务管理/Chapter 3.1 - 核心任务管理.md",
            "/uc-os-ii-code-notes/Chapter 3 - 任务管理/Chapter 3.2 - 用户任务管理.md",
          ],
        },
        {
          text: "Chapter 4 - 中断与时间管理",
          children: [
            "/uc-os-ii-code-notes/Chapter 4 - 中断与时间管理/Chapter 4 - 中断与时间管理.md",
          ],
        },
        {
          text: "Chapter 5 - 事件控制块",
          children: [
            "/uc-os-ii-code-notes/Chapter 5 - 事件控制块/Chapter 5 - 事件控制块.md",
          ],
        },
        {
          text: "Chapter 6 - 信号量与互斥信号量管理",
          children: [
            "/uc-os-ii-code-notes/Chapter 6 - 信号量与互斥信号量管理/Chapter 6.1 - 信号量管理.md",
            "/uc-os-ii-code-notes/Chapter 6 - 信号量与互斥信号量管理/Chapter 6.2 - 互斥信号量管理.md",
          ],
        },
        {
          text: "Chapter 7 - 消息管理",
          children: [
            "/uc-os-ii-code-notes/Chapter 7 - 消息管理/Chapter 7.1 - 消息邮箱管理.md",
            "/uc-os-ii-code-notes/Chapter 7 - 消息管理/Chapter 7.2 - 消息队列管理.md",
          ],
        },
        {
          text: "Chapter 8 - 事件标志组",
          children: [
            "/uc-os-ii-code-notes/Chapter 8 - 事件标志组/Chapter 8 - 事件标志组.md",
          ],
        },
        {
          text: "Chapter 9 - 内存管理",
          children: [
            "/uc-os-ii-code-notes/Chapter 9 - 内存管理/Chapter 9 - 内存管理.md",
          ],
        },
      ],
    },
  ],
  "/understanding-the-jvm-notes/": [
    {
      text: "☕ Understanding the JVM",
      link: "/understanding-the-jvm-notes/README.md",
      children: [
        {
          text: "Part 2 - 自动内存管理",
          children: [
            "/understanding-the-jvm-notes/Part 2 - 自动内存管理/Chapter 2 - Java 内存区域与内存溢出异常.md",
            "/understanding-the-jvm-notes/Part 2 - 自动内存管理/Chapter 3.1-3.2 - 概述 && 对象已死.md",
            "/understanding-the-jvm-notes/Part 2 - 自动内存管理/Chapter 3.3-3.4 - 垃圾收集算法 && HotSpot 的算法实现细节.md",
            "/understanding-the-jvm-notes/Part 2 - 自动内存管理/Chapter 3.5 - 经典垃圾收集器.md",
            "/understanding-the-jvm-notes/Part 2 - 自动内存管理/Chapter 3.6 - 低延迟垃圾收集器.md",
          ],
        },
        {
          text: "Part 3 - 虚拟机执行子系统",
          children: [
            "/understanding-the-jvm-notes/Part 3 - 虚拟机执行子系统/Chapter 6 - 类文件结构.md",
            "/understanding-the-jvm-notes/Part 3 - 虚拟机执行子系统/Chapter 7 - 虚拟机类加载机制.md",
            "/understanding-the-jvm-notes/Part 3 - 虚拟机执行子系统/Chapter 8.1-8.2 - 运行时栈帧结构.md",
            "/understanding-the-jvm-notes/Part 3 - 虚拟机执行子系统/Chapter 8.3 函数调用.md",
            "/understanding-the-jvm-notes/Part 3 - 虚拟机执行子系统/Chapter 8.5 - 基于栈的字节码解释执行引擎.md",
            "/understanding-the-jvm-notes/Part 3 - 虚拟机执行子系统/Chapter 9.2 - Tomcat - 正统的类加载器架构.md",
          ],
        },
        {
          text: "Part 4 - 程序编译与代码优化",
          children: [
            "/understanding-the-jvm-notes/Part 4 - 程序编译与代码优化/Chapter 10 - 前端编译与优化.md",
            "/understanding-the-jvm-notes/Part 4 - 程序编译与代码优化/Chapter 11.2 - 即时编译器.md",
            "/understanding-the-jvm-notes/Part 4 - 程序编译与代码优化/Chapter 11.3-11.4 - 提前编译器 && 编译器优化技术.md",
          ],
        },
        {
          text: "Part 5 - 高效并发",
          children: [
            "/understanding-the-jvm-notes/Part 5 - 高效并发/Chapter 12.3 - Java 内存模型.md",
            "/understanding-the-jvm-notes/Part 5 - 高效并发/Chapter 12.4-12.5 - Java 线程与协程.md",
            "/understanding-the-jvm-notes/Part 5 - 高效并发/Chapter 13 - 线程安全与锁优化.md",
          ],
        },
      ],
    },
  ],
  "/redis-implementation-notes/": [
    {
      text: "⛸️ Redis Implementation",
      link: "/redis-implementation-notes/README.md",
      children: [
        {
          text: "Part 1 - 数据结构与对象",
          children: [
            "/redis-implementation-notes/Part 1 - 数据结构与对象/Chapter 2 - 简单动态字符串.md",
            "/redis-implementation-notes/Part 1 - 数据结构与对象/Chapter 3 - 链表.md",
            "/redis-implementation-notes/Part 1 - 数据结构与对象/Chapter 4 - 字典.md",
            "/redis-implementation-notes/Part 1 - 数据结构与对象/Chapter 5 - 跳跃表.md",
            "/redis-implementation-notes/Part 1 - 数据结构与对象/Chapter 6 - 整数集合.md",
            "/redis-implementation-notes/Part 1 - 数据结构与对象/Chapter 7 - 压缩列表.md",
            "/redis-implementation-notes/Part 1 - 数据结构与对象/Chapter 8 - 对象.md",
          ],
        },
        {
          text: "Part 2 - 单机数据库的实现",
          children: [
            "/redis-implementation-notes/Part 2 - 单机数据库的实现/Chapter 9 - 数据库.md",
            "/redis-implementation-notes/Part 2 - 单机数据库的实现/Chapter 10 - RDB 持久化.md",
            "/redis-implementation-notes/Part 2 - 单机数据库的实现/Chapter 11 - AOF 持久化.md",
            "/redis-implementation-notes/Part 2 - 单机数据库的实现/Chapter 12 - 事件.md",
            "/redis-implementation-notes/Part 2 - 单机数据库的实现/Chapter 13 - 客户端.md",
            "/redis-implementation-notes/Part 2 - 单机数据库的实现/Chapter 14 - 服务器.md",
          ],
        },
        {
          text: "Part 3 - 多机数据库的实现",
          children: [
            "/redis-implementation-notes/Part 3 - 多机数据库的实现/Chapter 15 - 复制.md",
            "/redis-implementation-notes/Part 3 - 多机数据库的实现/Chapter 16 - Sentinel.md",
            "/redis-implementation-notes/Part 3 - 多机数据库的实现/Chapter 17 - 集群.md",
          ],
        },
        {
          text: "Part 4 - 独立功能的实现",
          children: [
            "/redis-implementation-notes/Part 4 - 独立功能的实现/Chapter 18 - 发布与订阅.md",
            "/redis-implementation-notes/Part 4 - 独立功能的实现/Chapter 19 - 事务.md",
            "/redis-implementation-notes/Part 4 - 独立功能的实现/Chapter 21 - 排序.md",
            "/redis-implementation-notes/Part 4 - 独立功能的实现/Chapter 22 - 二进制位数组.md",
            "/redis-implementation-notes/Part 4 - 独立功能的实现/Chapter 23 - 慢查询日志.md",
          ],
        },
      ],
    },
  ],
  "/understanding-nginx-notes/": [
    {
      text: "🗜️ Understanding Nginx",
      link: "/understanding-nginx-notes/README.md",
      children: [
        {
          text: "Part 1 - Nginx 能帮我们做什么",
          children: [
            "/understanding-nginx-notes/Part 1 - Nginx 能帮我们做什么/Chapter 1 - 研究 Nginx 前的准备工作.md",
            "/understanding-nginx-notes/Part 1 - Nginx 能帮我们做什么/Chapter 2 - Nginx 的配置.md",
          ],
        },
        {
          text: "Part 2 - 如何编写 HTTP 模块",
          children: [
            "/understanding-nginx-notes/Part 2 - 如何编写 HTTP 模块/Chapter 7 - Nginx 提供的高级数据结构.md",
          ],
        },
        {
          text: "Part 3 - 深入 Nginx",
          children: [
            "/understanding-nginx-notes/Part 3 - 深入 Nginx/Chapter 8.1-8.2 - Nginx 基础架构.md",
            "/understanding-nginx-notes/Part 3 - 深入 Nginx/Chapter 8.3-8.6 - Nginx 框架核心结构体.md",
            "/understanding-nginx-notes/Part 3 - 深入 Nginx/Chapter 8.7 - Nginx 内存池.md",
            "/understanding-nginx-notes/Part 3 - 深入 Nginx/Chapter 9.1-9.3 - 事件处理框架.md",
            "/understanding-nginx-notes/Part 3 - 深入 Nginx/Chapter 9.4-9.6 - 事件驱动模块与 EPOLL.md",
            "/understanding-nginx-notes/Part 3 - 深入 Nginx/Chapter 9.7-9.8 - 定时器事件与事件驱动框架处理流程.md",
            "/understanding-nginx-notes/Part 3 - 深入 Nginx/Chapter 9.9-9.10 - 文件的异步 IO 与 TCP.md",
            "/understanding-nginx-notes/Part 3 - 深入 Nginx/Chapter 10.1-10.2 - HTTP 框架的配置解析与合并.md",
            "/understanding-nginx-notes/Part 3 - 深入 Nginx/Chapter 10.3-10.7 - HTTP 阶段划分与框架初始化.md",
            "/understanding-nginx-notes/Part 3 - 深入 Nginx/Chapter 11 - HTTP 框架的执行流程.md",
            "/understanding-nginx-notes/Part 3 - 深入 Nginx/Chapter 12.1-12.4 - Upstream 与上游服务器通信.md",
            "/understanding-nginx-notes/Part 3 - 深入 Nginx/Chapter 12.5 - 接收上游服务器响应并处理.md",
            "/understanding-nginx-notes/Part 3 - 深入 Nginx/Chapter 12.6 - 12.9 - 转发响应并结束请求.md",
            "/understanding-nginx-notes/Part 3 - 深入 Nginx/Chapter 13.1-13.5 - 邮件代理模块 - 认证服务器.md",
            "/understanding-nginx-notes/Part 3 - 深入 Nginx/Chapter 13.6-13.7 - 邮件代理模块 - 上游.md",
            "/understanding-nginx-notes/Part 3 - 深入 Nginx/Chapter 14 - 进程间通信机制.md",
            "/understanding-nginx-notes/Part 3 - 深入 Nginx/Chapter 16 - slab 共享内存.md",
          ],
        },
      ],
    },
  ],
  "/netty-in-action-notes/": [
    {
      text: "⚙️ Netty in Action",
      link: "/netty-in-action-notes/README.md",
      children: [
        "/netty-in-action-notes/1 - NIO Transportation Model.md",
        "/netty-in-action-notes/2 - ByteBuf.md",
        "/netty-in-action-notes/3 - Netty Thread Model.md",
        "/netty-in-action-notes/3.1 - EventExecutorGroup.md",
        "/netty-in-action-notes/3.2 - EventLoopGroup.md",
        "/netty-in-action-notes/3.3 - EventExecutor.md",
        "/netty-in-action-notes/3.4 - EventLoop.md",
        "/netty-in-action-notes/4 - Channel Concept.md",
        "/netty-in-action-notes/4.1 - Channel.md",
        "/netty-in-action-notes/4.2 - ChannelHandler.md",
        "/netty-in-action-notes/4.3 - ChannelHandlerContext.md",
        "/netty-in-action-notes/4.4 - ChannelPipeline.md",
        "/netty-in-action-notes/5.1 - Future.md",
        "/netty-in-action-notes/5.2 - CompleteFuture.md",
        "/netty-in-action-notes/5.3 - FutureListener.md",
      ],
    },
  ],
  "/spring-microservices-notes/": [
    {
      text: "☁️ Spring Microservices",
      link: "/spring-microservices-notes/README.md",
      children: [
        "/spring-microservices-notes/Chapter 1 - 欢迎迈入云世界，Spring.md",
        "/spring-microservices-notes/Chapter 2 - 使用 Spring Boot 构建微服务.md",
        "/spring-microservices-notes/Chapter 3 - 使用 Spring Cloud 配置服务器控制配置.md",
        "/spring-microservices-notes/Chapter 4 - 服务发现.md",
        "/spring-microservices-notes/Chapter 5 - 使用 Spring Cloud 和 Netflix Hystrix 的客户端弹性模式.md",
        "/spring-microservices-notes/Chapter 6 - 使用 Spring Cloud 和 Zuul 进行服务路由.md",
        "/spring-microservices-notes/Chapter 7 - 保护微服务.md",
        "/spring-microservices-notes/Chapter 8 - 使用 Spring Cloud Stream 的事件驱动架构.md",
      ],
    },
  ],
  "/the-annotated-stl-sources-notes/": [
    {
      text: "⚒️ The Annotated STL Sources",
      link: "/the-annotated-stl-sources-notes/README.md",
      children: [
        {
          text: "Chapter 1 - STL 概论与版本简介",
          children: [
            "/the-annotated-stl-sources-notes/Chapter 1 - STL 概论与版本简介/Chapter 1 - STL 概论与版本简介.md",
          ],
        },
        {
          text: "Chapter 2 - 空间分配器 allocator",
          children: [
            "/the-annotated-stl-sources-notes/Chapter 2 - 空间分配器 allocator/Chapter 2.1 - SGI 空间分配器.md",
            "/the-annotated-stl-sources-notes/Chapter 2 - 空间分配器 allocator/Chapter 2.2 - SGI 特殊的空间分配器.md",
            "/the-annotated-stl-sources-notes/Chapter 2 - 空间分配器 allocator/Chapter 2.3 - 内存基本处理工具.md",
          ],
        },
        {
          text: "Chapter 3 - 迭代器概念与 traits 编程方法",
          children: [
            "/the-annotated-stl-sources-notes/Chapter 3 - 迭代器概念与 traits 编程方法/Chapter 3.1-3.5 - 迭代器设计思维.md",
            "/the-annotated-stl-sources-notes/Chapter 3 - 迭代器概念与 traits 编程方法/Chapter 3.6 - iterator 源代码完整重列.md",
            "/the-annotated-stl-sources-notes/Chapter 3 - 迭代器概念与 traits 编程方法/Chapter 3.7 - SGI STL 的私房菜：__type_traits.md",
          ],
        },
        {
          text: "Chapter 4 - 序列式容器",
          children: [
            "/the-annotated-stl-sources-notes/Chapter 4 - 序列式容器/Chapter 4.2 - vector.md",
            "/the-annotated-stl-sources-notes/Chapter 4 - 序列式容器/Chapter 4.3 - list.md",
            "/the-annotated-stl-sources-notes/Chapter 4 - 序列式容器/Chapter 4.4 - deque.md",
            "/the-annotated-stl-sources-notes/Chapter 4 - 序列式容器/Chapter 4.5 - stack.md",
            "/the-annotated-stl-sources-notes/Chapter 4 - 序列式容器/Chapter 4.6 - queue.md",
            "/the-annotated-stl-sources-notes/Chapter 4 - 序列式容器/Chapter 4.7 - heap.md",
            "/the-annotated-stl-sources-notes/Chapter 4 - 序列式容器/Chapter 4.8 - priority_queue.md",
            "/the-annotated-stl-sources-notes/Chapter 4 - 序列式容器/Chapter 4.9 - slist.md",
          ],
        },
        {
          text: "Chapter 5 - 关联式容器",
          children: [
            "/the-annotated-stl-sources-notes/Chapter 5 - 关联式容器/Chapter 5.2 - RB-Tree.md",
            "/the-annotated-stl-sources-notes/Chapter 5 - 关联式容器/Chapter 5.3 - set & multiset.md",
            "/the-annotated-stl-sources-notes/Chapter 5 - 关联式容器/Chapter 5.4 - map & multimap.md",
            "/the-annotated-stl-sources-notes/Chapter 5 - 关联式容器/Chapter 5.7 - hashtable.md",
            "/the-annotated-stl-sources-notes/Chapter 5 - 关联式容器/Chapter 5.8 - hash_set.md",
            "/the-annotated-stl-sources-notes/Chapter 5 - 关联式容器/Chapter 5.9 - hash_map.md",
            "/the-annotated-stl-sources-notes/Chapter 5 - 关联式容器/Chapter 5.10 - hash_multiset.md",
            "/the-annotated-stl-sources-notes/Chapter 5 - 关联式容器/Chapter 5.11 - hash_multimap.md",
          ],
        },
        {
          text: "Chapter 6 - 算法",
          children: [
            "/the-annotated-stl-sources-notes/Chapter 6 - 算法/Chapter 6.1-6.3 - 数值算法.md",
            "/the-annotated-stl-sources-notes/Chapter 6 - 算法/Chapter 6.4 - 基本算法.md",
            "/the-annotated-stl-sources-notes/Chapter 6 - 算法/Chapter 6.5 - set 相关算法.md",
            "/the-annotated-stl-sources-notes/Chapter 6 - 算法/Chapter 6.7.1 - 数据处理算法.md",
            "/the-annotated-stl-sources-notes/Chapter 6 - 算法/Chapter 6.7.2 - lower_bound.md",
            "/the-annotated-stl-sources-notes/Chapter 6 - 算法/Chapter 6.7.3 - upper_bound.md",
            "/the-annotated-stl-sources-notes/Chapter 6 - 算法/Chapter 6.7.5 - permutation.md",
            "/the-annotated-stl-sources-notes/Chapter 6 - 算法/Chapter 6.7.7 - random_shuffle.md",
            "/the-annotated-stl-sources-notes/Chapter 6 - 算法/Chapter 6.7.8 - partial_sort.md",
            "/the-annotated-stl-sources-notes/Chapter 6 - 算法/Chapter 6.7.9 - sort.md",
            "/the-annotated-stl-sources-notes/Chapter 6 - 算法/Chapter 6.7.12 - nth_element.md",
          ],
        },
        {
          text: "Chapter 7 - 仿函数 functors",
          children: [
            "/the-annotated-stl-sources-notes/Chapter 7 - 仿函数 functors/Chapter 7 - functors.md",
          ],
        },
        {
          text: "Chapter 8 - 适配器",
          children: [
            "/the-annotated-stl-sources-notes/Chapter 8 - 适配器/Chapter 8.1-8.2 - Container Adapters.md",
            "/the-annotated-stl-sources-notes/Chapter 8 - 适配器/Chapter 8.3 - Iterator Adapters.md",
            "/the-annotated-stl-sources-notes/Chapter 8 - 适配器/Chapter 8.4 - Function Adapters.md",
          ],
        },
      ],
    },
  ],
  "/jdk-source-code-analysis/": [
    {
      text: "☕ Java Development Kit 8",
      link: "/jdk-source-code-analysis/README.md",
      children: [
        {
          text: "java.io",
          children: [
            "/jdk-source-code-analysis/java.io/Abstract Class - java.io.InputStream.md",
            "/jdk-source-code-analysis/java.io/Abstract Class - java.io.OutputStream.md",
            "/jdk-source-code-analysis/java.io/Abstract Class - java.io.Reader.md",
            "/jdk-source-code-analysis/java.io/Class - java.io.BufferedInputStream.md",
            "/jdk-source-code-analysis/java.io/Class - java.io.BufferedOutputStream.md",
            "/jdk-source-code-analysis/java.io/Class - java.io.BufferedReader.md",
            "/jdk-source-code-analysis/java.io/Class - java.io.ByteArrayInputStream.md",
            "/jdk-source-code-analysis/java.io/Class - java.io.ByteArrayOutputStream.md",
            "/jdk-source-code-analysis/java.io/Class - java.io.DataInputStream.md",
            "/jdk-source-code-analysis/java.io/Class - java.io.DataOutputStream.md",
            "/jdk-source-code-analysis/java.io/Class - java.io.FileInputStream.md",
            "/jdk-source-code-analysis/java.io/Class - java.io.FileOutputStream.md",
            "/jdk-source-code-analysis/java.io/Class - java.io.FileReader.md",
            "/jdk-source-code-analysis/java.io/Class - java.io.FilterInputStream.md",
            "/jdk-source-code-analysis/java.io/Class - java.io.FilterOutputStream.md",
            "/jdk-source-code-analysis/java.io/Class - java.io.InputStreamReader.md",
            "/jdk-source-code-analysis/java.io/Class - java.io.PipedInputStream.md",
            "/jdk-source-code-analysis/java.io/Class - java.io.PipedOutputStream.md",
            "/jdk-source-code-analysis/java.io/Class - java.io.PushbackInputStream.md",
            "/jdk-source-code-analysis/java.io/Class - java.io.SequenceInputStream.md",
            "/jdk-source-code-analysis/java.io/Interface - java.io.Closeable.md",
          ],
        },
        {
          text: "java.lang",
          children: [
            "/jdk-source-code-analysis/java.lang/Abstract Class - java.lang.AbstractStringBuilder.md",
            "/jdk-source-code-analysis/java.lang/Class - java.lang.Integer.md",
            "/jdk-source-code-analysis/java.lang/Class - java.lang.String.md",
            "/jdk-source-code-analysis/java.lang/Class - java.lang.ThreadLocal.md",
          ],
        },
        {
          text: "java.nio",
          children: [
            "/jdk-source-code-analysis/java.nio/Abstract Class - java.nio.Buffer.md",
          ],
        },
        {
          text: "java.util",
          children: [
            "/jdk-source-code-analysis/java.util/Abstract Class - java.util.AbstractCollection.md",
            "/jdk-source-code-analysis/java.util/Abstract Class - java.util.AbstractList.md",
            "/jdk-source-code-analysis/java.util/Abstract Class - java.util.AbstractMap.md",
            "/jdk-source-code-analysis/java.util/Abstract Class - java.util.AbstractQueue.md",
            "/jdk-source-code-analysis/java.util/Abstract Class - java.util.AbstractSet.md",
            "/jdk-source-code-analysis/java.util/Class - java.util.ArrayList.md",
            "/jdk-source-code-analysis/java.util/Class - java.util.HashMap.md",
            "/jdk-source-code-analysis/java.util/Class - java.util.HashSet.md",
            "/jdk-source-code-analysis/java.util/Class - java.util.IdentityHashMap.md",
            "/jdk-source-code-analysis/java.util/Class - java.util.LinkedHashMap.md",
            "/jdk-source-code-analysis/java.util/Class - java.util.LinkedHashSet.md",
            "/jdk-source-code-analysis/java.util/Class - java.util.LinkedList.md",
            "/jdk-source-code-analysis/java.util/Class - java.util.PriorityQueue.md",
            "/jdk-source-code-analysis/java.util/Class - java.util.TreeMap.md",
            "/jdk-source-code-analysis/java.util/Class - java.util.TreeSet.md",
            "/jdk-source-code-analysis/java.util/Interface - java.util.Collection.md",
            "/jdk-source-code-analysis/java.util/Interface - java.util.Deque.md",
            "/jdk-source-code-analysis/java.util/Interface - java.util.Iterator.md",
            "/jdk-source-code-analysis/java.util/Interface - java.util.ListIterator.md",
            "/jdk-source-code-analysis/java.util/Interface - java.util.Map.md",
            "/jdk-source-code-analysis/java.util/Interface - java.util.NavigableMap.md",
            "/jdk-source-code-analysis/java.util/Interface - java.util.NavigableSet.md",
            "/jdk-source-code-analysis/java.util/Interface - java.util.Queue.md",
            "/jdk-source-code-analysis/java.util/Interface - java.util.Set.md",
            "/jdk-source-code-analysis/java.util/Interface - java.util.SortedMap.md",
            "/jdk-source-code-analysis/java.util/Interface - java.util.SortedSet.md",
          ],
        },
        {
          text: "java.util.concurrent",
          children: [
            "/jdk-source-code-analysis/java.util.concurrent/Abstract Class - java.util.concurrent.atomic.AtomicIntegerFieldUpdater.md",
            "/jdk-source-code-analysis/java.util.concurrent/Abstract Class - java.util.concurrent.locks.AbstractExecutorService.md",
            "/jdk-source-code-analysis/java.util.concurrent/Abstract Class - java.util.concurrent.locks.AbstractOwnableSynchronizer.md",
            "/jdk-source-code-analysis/java.util.concurrent/Abstract Class - java.util.concurrent.locks.AbstractQueuedSynchronizer.md",
            "/jdk-source-code-analysis/java.util.concurrent/Class - java.util.concurrent.ArrayBlockingQueue.md",
            "/jdk-source-code-analysis/java.util.concurrent/Class - java.util.concurrent.ConcurrentHashMap.md",
            "/jdk-source-code-analysis/java.util.concurrent/Class - java.util.concurrent.ConcurrentLinkedQueue.md",
            "/jdk-source-code-analysis/java.util.concurrent/Class - java.util.concurrent.DelayQueue.md",
            "/jdk-source-code-analysis/java.util.concurrent/Class - java.util.concurrent.ExecutorCompletionService.md",
            "/jdk-source-code-analysis/java.util.concurrent/Class - java.util.concurrent.FutureTask.md",
            "/jdk-source-code-analysis/java.util.concurrent/Class - java.util.concurrent.LinkedBlockingQueue.md",
            "/jdk-source-code-analysis/java.util.concurrent/Class - java.util.concurrent.LinkedTransferQueue.md",
            "/jdk-source-code-analysis/java.util.concurrent/Class - java.util.concurrent.SynchronousQueue.md",
            "/jdk-source-code-analysis/java.util.concurrent/Class - java.util.concurrent.ThreadPoolExecutor.md",
            "/jdk-source-code-analysis/java.util.concurrent/Class - java.util.concurrent.atomic.AtomicInteger.md",
            "/jdk-source-code-analysis/java.util.concurrent/Class - java.util.concurrent.atomic.AtomicIntegerArray.md",
            "/jdk-source-code-analysis/java.util.concurrent/Class - java.util.concurrent.atomic.AtomicReference.md",
            "/jdk-source-code-analysis/java.util.concurrent/Class - java.util.concurrent.atomic.AtomicStampedReference.md",
            "/jdk-source-code-analysis/java.util.concurrent/Class - java.util.concurrent.locks.ReentrantLock.md",
            "/jdk-source-code-analysis/java.util.concurrent/Class - java.util.concurrent.locks.ReentrantReadWriteLock.md",
            "/jdk-source-code-analysis/java.util.concurrent/Interface - java.util.concurrent.BlockingQueue.md",
            "/jdk-source-code-analysis/java.util.concurrent/Interface - java.util.concurrent.CompletionService.md",
            "/jdk-source-code-analysis/java.util.concurrent/Interface - java.util.concurrent.Executor.md",
            "/jdk-source-code-analysis/java.util.concurrent/Interface - java.util.concurrent.ExecutorService.md",
            "/jdk-source-code-analysis/java.util.concurrent/Interface - java.util.concurrent.Future.md",
            "/jdk-source-code-analysis/java.util.concurrent/Interface - java.util.concurrent.ScheduledExecutorService.md",
            "/jdk-source-code-analysis/java.util.concurrent/Interface - java.util.concurrent.TransferQueue.md",
            "/jdk-source-code-analysis/java.util.concurrent/Interface - java.util.concurrent.locks.Lock.md",
            "/jdk-source-code-analysis/java.util.concurrent/Interface - java.util.concurrent.locks.ReadWriteLock.md",
          ],
        },
      ],
    },
  ],
};
